name: phonecallstate_example
description: Demonstrates how to use the phonecallstate plugin.

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  phonecallstate:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
